CodeSquad mastering javascript 2주차 todoList 1차 커밋
code-squad/masteringjs_todo pull request #1
Opened 2018-09-10 08:05 UTC by jeonghoyoo

- functional programming 방향을 잡기 위한 리뷰를 받기 위한 1차 커밋
- 계속해서 리팩토링해야 할 듯으로 판단

2018-09-10 22:42 UTC, crongro requested changes
👍 
PIPE와 커리를 잘 시도하셨어요.

커리는 커리된 함수를 가지고 다니면서 다른곳에서  추가로 인자를 받아서 쓰기 위해서 좀더 많이 쓰여요. (아주 활용도가 높은건 아니지만요)

함수크기가 큰녀석들은 좀더 줄여보시면 좋겠고요.
그리고나서,
pipe를 한군데라도 좀더 추가로 써볼때가 있는지 찾아서 적용해보세요. 메인로직에서만 쓰이는 건 아닐테니까요.

2018-09-10 22:42 UTC, nigayo commented on todoList.html
> +const TODO_INFO_INDEX = {
상수로 선언된 객체선언부가 이름이 너무 길어서 코드볼때 어려움이 있네요.
이처럼 네임스페이스를 만들면 중복이름을 줄이는 게 좋아요.


const TODO_INFO_IDX = {
  COMMAND : 0,
  ADD_TITLE : 1
}

//사용시
TODO_INFO_IDX.COMMAND = 2;

2018-09-10 22:42 UTC, nigayo commented on todoList.html
> +const COMMAND_OPTION = {
전체적으로  이름중복을 제거해보시면 좋겠어요.여기서는 command가 중복이네요.

2018-09-10 22:42 UTC, nigayo commented on todoList.html
> +    let todoJobCurryImple;
일단 커리를 잘 만드셨고, 호출까지 잘 하셨어요!

그런데, 여기서 todoJobCurryImple를 결과를 받지만 무언가 다른데서 쓰이는게 없는거 같은데요?

impleAddCommand나 impleShowCommand 등의 함수는 인자가 하나만 필요한 거 같아서,
 impleShowCommand(optionArr) 로 바로 호출해도 될거 같긴해요.

2018-09-10 22:42 UTC, nigayo commented on todoList.html
> +const todoJobCurry = (firstFunc) => (...firstArgs) => secondFunc => (...secondArgs) =>{
네 원리를 잘 이해하신 거 같네요.

2018-09-10 22:42 UTC, nigayo commented on todoList.html
> +const impleUpdateCommand = (optionArr) => {
implement 처럼 쓰세요. 동사는  잘 안줄여씁니다.

2018-09-10 22:42 UTC, nigayo commented on todoList.html
> +    if(commandStr === COMMAND_OPTION.COMMAND_ADD){
여기에 조건문이 있는건 좀 아쉽지만, 조건상황이 무엇인지 드러내서 그런측면에선 좋네요.

2018-09-10 22:42 UTC, nigayo commented on todoList.html
> +const commandPipe = (...functions) => args => {
비지니스로직과  상관없는 유틸리티와 같은 함수들을 잘 만드셨고요.
이런성격의 함수들은 위쪽으로 몰아서 배치해보시죠.

2018-09-10 22:42 UTC, nigayo commented on todoList.html
> +    commandPipe(
짝짝짝

2018-09-10 22:42 UTC, nigayo commented on todoList.html
> +const printDetailInfoWithCommand = (commandStr, filteredMap = null) => {
중첩된 조건문이  조금 깊어서 아쉽네요.
할 수 있다면 개선해보면 좋겠어요. 안되면.. 함수로 분리하는 거죠.

2018-09-10 22:42 UTC, nigayo commented on todoList.html
> +    let returnStr = "";
의미있는 이름으로.. returnStr보다는.

2018-09-11 00:13 UTC, jeonghoyoo commented
리뷰남겨주신 내용 살펴보고 익일안에 재 푸시 하겠습니다. 감사합니다.

2018-09-28 01:14 UTC, crongro approved these changes
함수가 좀 큰 녀석들이 보이고, 중첩된 코드(조건문이나 반복문)이 보여서 좀 아쉬웠습니다.
하지만 클래스를 역할별로 나누고, 그 안에서 함수형기법으로 구현한 시도가 상당히 좋았어요.
리뷰 남겨드린 것은 나중에 좀더 참고해서 수정해보세요.

승인/머지 합니다. ^^
수고하셨어요.

2018-09-28 01:14 UTC, nigayo commented on todoList.html
> +        if(commandStr === COMMAND_OPTION.ADD){
COMMAND_OPTION 객체보면 add:add 이런식으로 key-value가 같은상태인데요.
그런객체매핑을 없애고 , 
 if(commandStr === "add"){}
라고 해도 될 거 같아요.

2018-09-28 01:14 UTC, nigayo commented on todoList.html
> +const TodoCommon = class{
TodoCommon은 생성자가 필요 없는 클래스네요.
일관성을 위해서 class 문법을 사용할 수 있지만, 
이렇게 생성자도 필요없는 유틸리티모음은 객체리터럴로 표현하는 것도 좋아보입니다.

2018-09-28 01:14 UTC, nigayo commented on todoList.html
> +        if(timeFlag === "H"){
if분이 필요할수밖에 없군요.
하지만, 아래 코드가 반복문마다 보이네요.
 return  calcValue > 0 ? (calcValue + "시간") : "";

calcValue<=0 이조건을 먼저 체크해서 틀리면 return해주는 건 어때요?

2018-09-28 01:14 UTC, nigayo commented on todoList.html
> +        this.todoCommon = new TodoCommon();
클래스가 다른 클래스를 필요로 할때, 일반적으로 이렇게 클래스 안에서 다른클래스를 초기화하지 않고, 
외부에서 선언해서 주입받는게 좀더 의존성을 낮춥니다.

a  = new A();
new B(a);

2018-09-28 01:14 UTC, nigayo commented on todoList.html
> +            todoListArr.forEach((mapInfo, index) => {
중첩된 코드가 좀 보입니다.
forEach의 인자로 받는 함수를 분리해서 선언하면 중첩된 코드가 좀더 보기 좋아질거 같아요.

2018-09-28 01:14 UTC, nigayo commented on todoList.html
> +        todoListArr.some((todoInfo, index) => {
some 함수가 boolean타입을 반환할텐데요, 그것을 사용하지 않는 코드네요.
그 점은 some을 제대로 용도에 맞게 사용한것인지 생각하게 됩니다. 
이와 같은 함수들모두 용도를 조금더 고민(특히 반환값)하면서 사용해보세요.

2018-09-28 01:14 UTC, nigayo commented on todoList.html
> +        }else if(commandStr === COMMAND_OPTION.SHOW){
여기 아래 분기문이 중첩되어 있어서 코드를 보기 어렵네요.

분기문을 없앨 수 있다면 더 좋지만 그렇지 않다면 하위함수로 분리하는 것이 방법입니다.

이만큼을 별도 함수로 분리해보면 좋겠어요.

```javascript
    if(filteredMap === null || filteredMap.length === 0){
                console.log("요청하신 Show 명령어에 대한 Task가 없습니다.");
            }else{
                let showPrintStr = "";
                filteredMap.forEach((mapInfo, index) => {
                    index > 0 ? showPrintStr += `,` : ``;
                    showPrintStr += `'${mapInfo.id}, ${mapInfo.title}` 
                    showPrintStr += (mapInfo.state === TASK_STATE.DONE) ? ", "+this.todoCommon.getWorkingHoursFormat(mapInfo.startTime, mapInfo.finishTime)+"'" : "'";
                });
                console.log(showPrintStr);
            }
```

2018-09-28 01:14 UTC, merged