2주차 과제 1차 pr 드립니다.
code-squad/masteringjs_todo pull request #10
Opened 2018-09-18 15:19 UTC by jjori-master

감사합니다. :)

2018-09-19 08:22 UTC, crongro requested changes
좋은 코드네요.

함수형+객체지향을 잘 섞으셨는데요?
이 단계에서 좀더 함수형으로 연습을 해보면 좋겠습니다.

리뷰남겨드린대로 수정해보시고, 가급적 pipe를 써서 함수합성을 시도해보세요!

2018-09-19 08:22 UTC, crongro commented on todo.js
> +    return ids.push(null);
id를 생성하는데 null만 추가하고 있어서 불필요해보입니다.

2018-09-19 08:22 UTC, crongro commented on todo.js
> +    return ids.push(null);
배열에 자리를 확보해둘필요가 없습니다.

2018-09-19 08:22 UTC, crongro commented on todo.js
> +function Task(id, status, contents) {
Task 가 new로 불리면서, 생성자패턴을 사용하셨군요.
함수형관점에서는 클래스를 사용하지 않는게 일반적입니다. this를 통해서 상태관리를 잘 안하고요.
그래서 음 이 코드는 잘 보관해서 3주차미션으로 보내시고~, 생성자를 쓰지 않고 함수형으로 (여러개의 함수로) 구현하면 좋겠습니다.

2018-09-19 08:22 UTC, crongro commented on todo.js
> +        return [
return 뒤에 많은 코드는.. 좀 보기 어렵고, 디버깅(중간 값을 확인하기 어려워서요)에 불리한 코드에요.

2018-09-19 08:22 UTC, crongro commented on todo.js
> +        ].filter((diffTime) => {
배열 체이닝을 잘 하셨네요! filter-map 구조로요. 좋아요.

2018-09-19 08:22 UTC, crongro commented on todo.js
> +    fns[method](param1, param2);
객체관계로 요렇게 하신거 잘하셨어요! 
객체를 잘 매핑해두면 분기코드가 좀 줄어들죠.

2018-09-30 14:34 UTC, jjori-master reviewed
수정했습니다.~~

2018-10-07 12:23 UTC, crongro approved these changes
제가 리뷰를 놓친걸  이제 봤어요. 죄송합니다.
리뷰남겨드리고 승인합니다!

2018-10-07 12:23 UTC, crongro commented on todo.js
> +            tasks.push({
task.push (new Task(xx,yy));

이런식으로 Task 생성자를 만들어서 표현할 수도 있겠네요.

2018-10-07 12:23 UTC, crongro commented on todo.js
>              const targetTasks = tasks.filter((task) => {
잘 하셨는데요. 
한줄로 표현해두는 것이 보기는 더 좋죠.

const targetTasks = tasks.filter(filterFn).reduce(reduceFn)  

이런식으로 함수 선언부를 제외~

2018-10-07 12:23 UTC, crongro commented on todo.js
> +tasks[0].time.done = new Date(new Date().getTime() + (1000 * 27) + (1000 * 60 * 90) + (1000 * 60 * 60 * 24));
(1000 * 60 * 90) 이런녀석들도 변수에 이름을 담아두면 무엇인지  더 알기 쉬울 거 같아요~

2018-10-07 12:23 UTC, merged