to do list (ver.1) PR 보내드립니다.
code-squad/masteringjs_todo pull request #2
Opened 2018-09-11 11:28 UTC by uoon-dev

2018-09-11 13:36 UTC, crongro requested changes
함수가 명확하고 대체로 깔끔하네요.
잘하셨고요.

리뷰남겨드립니다. 
그리고 pipe를 좀더 학습하셔서 어딘가에 일부분이라도 한번 적용해보실래요?

2018-09-11 13:36 UTC, nigayo commented on todo.js
> +    case 2: {
2, 3은 의미를 알기는어렵지만, 음 지금은 그래도 구별할 수 있는 식별자 역할을 할 수 있어보여서 괜찮아보입니다.

2018-09-11 13:36 UTC, nigayo commented on todo.js
> +      eval(`${fn}('${state}')`); break;
eval 은 아시다시피 잘 쓰지 말라는 건데요. (scope가 좀 예상하기 어려운 구조라서)
원하시는 것을 하려면, 이렇게도 가능하십니다.(객체를 써야하고요)

```javascript
const methods = {
  add() {
    return "add";
  },
  update() {
   return "update";
  }
}

methods[commandValues[0].toLowerCase()](state);
```

2018-09-11 13:36 UTC, nigayo commented on todo.js
> +const toDoList = {
간결하지만 데이터 구조를 잘 잡았어요.

2018-09-11 13:36 UTC, nigayo commented on todo.js
> +const show = (state) => {
메서드들이 군더더기 없어서 좋습니다.

2018-09-11 13:36 UTC, nigayo commented on todo.js
> +    toDoList[item].forEach((value, key) => {
네 이렇게 하셔도 좋고, Object.keys를 사용해서 배열로 키값을 뽑아서 하셔도 좋고요.

2018-09-11 13:36 UTC, nigayo commented on todo.js
> +      if (value.index == id) {
forEach에서 조건상황을 추가할것이면, some을 쓰는 경우도 있긴해요.(break 가 되기때문에 낭비를 줄이죠)
그런데 배열이 크지 않다면 filter를 써도 되긴합니다.  
그리고나서 필터링된 결과를 가지고 job을 만들면, 지금 forEach에서 하고 있는 몇 가지 일을 단계별로 더 나누게 될 수 있을 거 같네요.

2018-09-11 13:36 UTC, nigayo commented on todo.js
> +let index = 1;
index보다 구체적인 이름이 좀더 낫겠어요.

2018-09-14 22:43 UTC, crongro approved these changes
업데이트 코드를 제가 놓쳤네요.

잘 개선하셨네요.
몇개 질문은 답변부탁드려요!

이제 앞으로 pipe 와 친해지시길 바랄게요~

2018-09-14 22:43 UTC, nigayo commented on todo.js
> +  switch(method) {
오! 잘 개선하셨네요.

2018-09-14 22:43 UTC, nigayo commented on todo.js
> +const command = (commandText) => {
👍

2018-09-14 22:43 UTC, nigayo commented on todo.js
> +        toDoList[unit].some((item, index) => {
여기서 some메서드를 사용하신 이유가? 좀 궁금합니다.

2018-09-14 22:43 UTC, nigayo commented on todo.js
> +    return 'add'
반환값을 사용하는 곳이 없는데 반환값을 주신 이유가 있을까요?

2018-09-14 22:43 UTC, merged

2018-09-15 02:56 UTC, uoon-dev commented on todo.js
> +        toDoList[unit].some((item, index) => {
"forEach에서 조건상황을 추가할것이면, some을 쓰는 경우도 있긴해요.(break 가 되기때문에 낭비를 줄이죠)" 라고 말씀하셔서 해본 건데 제가 이해를 잘못했나 봐요 ㅎㅎ..

2018-09-15 03:02 UTC, uoon-dev commented on todo.js
> +    return 'add'
그렇네요! 지우고 다시 push 할게요 ㅎㅜ

2018-09-17 02:53 UTC, nigayo commented on todo.js
> +        toDoList[unit].some((item, index) => {
오 아닙니다~ 생각이 궁금했을뿐이에요. ^^ 
이야기 하신것처럼 쓰는 경우도 있어요.