todo-list 리뷰 부탁 드립니다 :)
code-squad/masteringjs_todo pull request #7
Opened 2018-09-14 06:57 UTC by livelikeabel

show$done을 했을 때 시간을 같이 출력해 주는것은 아직 구현하지 못했습니다 ㅠㅠ

2018-09-14 22:12 UTC, crongro requested changes
함수형프로그래밍이 별거 아닙니다.
함수의 역할을 명확하게하고, 동작도 순수하게 만들고,
이를 조합하는것이죠.

이제, 
pipe를 사용해서 추가로! 개선해보면 좋겠습니다.

지금너무 잘 구현했지만, 일단 request changes 합니다.

2018-09-14 22:12 UTC, nigayo commented on todo.js
> +  totalStatus: {
이렇게 todo/doing 등의 상태를 계속 sync맞춰주는 건 어렵고 정확한 건 아닌 거 같아요.
필요할때 갯수를 count하면 좋겠습니다.

2018-09-14 22:12 UTC, nigayo commented on todo.js
> +  const [firstWord, secondWord, thirdWord] = refineSentence(orderSentence)
문법을 잘 쓰셨네요.

2018-09-14 22:12 UTC, nigayo commented on todo.js
> +  switch (firstWord) {
firstWord는 사실 command 라는 의미가 있으니, 이름을 좀더 의미있게 할 수 있겠군요.

2018-09-14 22:12 UTC, nigayo commented on todo.js
> +  sentence
method chaining 에 대해서 동작원리를 설명하실 수 있으면 좋겠어요.
 return 을 어떤것을 하면 가능한 것인지요.

2018-09-14 22:12 UTC, nigayo commented on todo.js
> +  increaseStatus(newTask.status)
이렇게 매번 업뎃을 해야하는 불편함이 있죠.

2018-09-14 22:12 UTC, nigayo commented on todo.js
> +const logAddResult = ({ id, taskTitle }) => {
이런 간략한 함수 좋아요.

2018-09-21 05:05 UTC, livelikeabel commented on todo.js
> +  sentence
객체가 (위의 코드에서는 배열 객체) 가지고 있는 메서드를 실행할 수 있는 걸로 알고 있습니다. 
제가 직접 method chaining 을 만든다면, return 을 현재 실행 컨텍스트인 객체 (this)를 리턴해주어, 계속해서 그 컨텍스트가 가진 메서드를 실행할 수 있게 하는 것이라고 알고 있습니다.
위에서는 계속해서 배열을 리턴해 주기 때문에, 배열의 메서드를 체이닝 해서 쓸 수 있는거 같습니다 

글로 설명하려고 하니 공부가 부족한거 같네요.. ㅎㅎㅎ 더 공부해서 확실히 알아보겠습니다!

2018-09-21 05:18 UTC, nigayo commented on todo.js
> +  sentence
잘 설명하셨어요.

2018-09-21 11:32 UTC, crongro approved these changes
잘 구현하셨네요.
칭찬리뷰를 더 많이 남깁니다 ㅎ

승인하고, 머지할게요!

2018-09-21 11:32 UTC, nigayo commented on todo.js
> +  const [command, arg1, arg2] = refineSentence(orderSentence)
arg1 과 arg2 가 이름을 지을 수 있었으면,, 좋았을텐데, 지금 그러기 어려운거죠? 아쉽네요~

2018-09-21 11:32 UTC, nigayo commented on todo.js
> +const forEachPipe = (...functions) => obj => functions.forEach(func => func(obj))
pipe라고 하면 되지, 왜 forEach와 같은 문법적인 방법이 이름이 들어갈까요..

2018-09-21 11:32 UTC, nigayo commented on todo.js
>  function add(taskTitle) {
함수표현식으로 작성하다가 add/show 등은 함수선언문이라 좀 어색해보여요.

2018-09-21 11:32 UTC, nigayo commented on todo.js
> +const compose = (...funcs) => param => funcs.reduceRight((acc,func) => func(acc), param)
compose와 pipe의 동작과 서로간의 차이는 이해하신 거죠? 

componse 와 pipe는 호불호가 있지만, 정하기 나름인거 같아요.
대체로 pipe를 좀더 일반적으로 많이 쓰는 거 같고요.

2018-09-21 11:32 UTC, nigayo commented on todo.js
> +  const copiedTodos = JSON.parse(JSON.stringify(todos))
오 이런것까지~ immutable한 방법을 여러가지 방법으로 익힐필요가 있습니다. 잘하셨네요.

2018-09-21 11:32 UTC, nigayo commented on todo.js
> +const findTodo = ({copiedTodos, taskId, statusType}) => {
네 그때그때 이런메서드들 만들어서 조합을 하려고 노력해보세요~

2018-09-21 11:32 UTC, merged