[리뷰요청] 미션. TODOLIST 만들기
code-squad/masteringjs_todo pull request #8
Opened 2018-09-15 00:20 UTC by devJang

아직 다하지는 못하였지만 시간이 늦어 뒤늦게 PR합니다!
차후에 확실히 완성하도록 하겠습니다

2018-09-15 03:46 UTC, crongro requested changes
잘 구현하고 계시네요
문법도 잘 이해하고 계시고요.

리뷰참고해서 이어서 쭉 해보시고요.
다시 커밋/푸시 하세요~

2018-09-15 03:46 UTC, nigayo commented on src/todo.js
> +})();
즉시실행함수로 내부함수를 보호하셨군요! 
잘했어요

2018-09-15 03:46 UTC, nigayo commented on src/todo.js
> +  const [action, ...args] = isReadyString.split('$');
destructuring을 잘 활용하셨네요.

2018-09-15 03:46 UTC, nigayo commented on src/todo.js
> +    tasks,
다른건 메서드인데,  tasks 는 배열이라 약간 어색해요.
일관성을 위해서라도 tasks를 메서드를 통해서 얻어오도록 하면 더 좋겠습니다.

2018-09-15 03:46 UTC, nigayo commented on src/todo.js
> +    return tasks.filter(stateType).reduce(showLog, '');
네 메서드 체이닝도 함수형프로그래밍에서 함수를 잘 엮어주는 방법이에요.
코드가 읽기 쉽게 됐네요.

2018-09-15 03:46 UTC, nigayo commented on src/todo.js
> +  })();
여기서도 즉시실행함수를 썼는데요, 늘 이렇게 함수로 감싸는게 꼭 필요한 건 아니에요.
굉장한 장점이 있는게 아니라서, 지금도 즉시실행함수 없이 구현해보면 좋겠다는 생각이 듭니다.

2018-09-28 01:30 UTC, crongro approved these changes
수고하셨어요.
잘 구현한 코드라 생각합니다~
리뷰남겨드렸어요.

2018-09-28 01:30 UTC, nigayo commented on src/todo.js
> +    const isDone = task.state === 'doing' && newState === 'done';
isDone 보다는 bDone 이 좀더 낫겠어요. is는 boolean을 판단하는 함수에 주로 사용해서요.

2018-09-28 01:30 UTC, nigayo commented on src/todo.js
>        tasks.find((task) => {
array의 find 메서드를 사용하신것이면..적절한 구현이 아닌 거 같아요.
find는 일치하는 원소를 반환하는데요. 

지금은 find의 반환값을 이용한 코드가 아닌 거 같네요.

2018-09-28 01:30 UTC, nigayo commented on src/todo.js
>        tasks.push({
push 메서드는 새로운 배열을 만들지는 않죠.
immutable 하게 만들려면, concat 이나 spread operator를 쓸 수 있습니다. 참고하세요~

2018-09-28 01:30 UTC, merged

2018-09-28 01:31 UTC, devJang commented
아직 미완성된 상태라 피드백 내용까지 보완해서 다시 PR 드리겠습니다
감사합니다:)

2018-09-29 02:06 UTC, devJang commented on src/todo.js
> +  })();
이 부분은 피드백 반영하면서 적용해보겠습니다!

2018-09-29 02:06 UTC, devJang commented on src/todo.js
> +    const isDone = task.state === 'doing' && newState === 'done';
오...감사합니다

2018-09-29 02:07 UTC, devJang commented on src/todo.js
>        tasks.find((task) => {
네 제가 놓친 부분입니다! 감사합니다

2018-09-29 02:09 UTC, devJang commented on src/todo.js
>        tasks.push({
새로운 task를 사용하는데도 굳이 불변성이 필요할까 싶었는데
다시 반영하도록하겠습니다~