TODOLIST 만들기 리뷰 요청드립니다.
code-squad/masteringjs_todo pull request #9
Opened 2018-09-18 14:54 UTC by hyeyoon

안녕하세요 크롱님! 
todolist 리뷰 요청드립니다. 리뷰 후에 좀 더 보완하려고 합니다 :)

2018-09-19 08:12 UTC, crongro requested changes
잘 하셨어요.
add/show/update등은 더 작은 단위함수로 
조금더 나눌 수 있을 거 같아요.
한번해보세요!

2018-09-19 08:12 UTC, nigayo commented on todolist.js
> +const pipe = (...functions) => args => functions.reduce((arg, nextFn) => nextFn(arg), args);
좋아요. 함수형 유틸리티를 몰아두고 관리하면 좋죠. (물리적으로 다른 파일로 두는 것이 물론 더 좋고요)

2018-09-19 08:12 UTC, nigayo commented on todolist.js
> +const arrangeCommand = array => {
별건 아닌데 파라미터를 array라고 쓰는건 좀 별로네요. 진짜 네이티브 Array와 이름이 헷갈립니다.

2018-09-19 08:12 UTC, nigayo commented on todolist.js
> +const command = pipe(
잘 쓰셨어요. 함수형때 말씀드렸듯이 command라는 것이 어떤과정으로 처리되는지 순서대로 코드에서 의도가 잘 드러나야 하는데,
지금은 3가지를 하는 것을 알 수 있죠.

2018-09-19 08:12 UTC, nigayo commented on todolist.js
> +      data.todos[index].endAt = new Date();
사소하지만 new Date()를 두 군데서 표현하지 말고 한군데서만 표현해서 변수로 담아둘 수 있겠네요.

2018-09-19 08:12 UTC, nigayo commented on todolist.js
> +const update = (array) => {
update안에서 findIndex로 filtering하고 있는데요, 
filter -> 다른함수에서이후처리,  이렇게 분리해서 로직을 구현할 수도 있겠네요

2018-09-19 08:12 UTC, nigayo commented on todolist.js
> +  if (todos.length) {
이부분도 분리할 수도 있습니다. 앞부분의 reduce처리결과까지 끝내고, 다른함수에서 출력을 담당하도록요.

2018-09-19 08:12 UTC, nigayo commented on todolist.js
> +    ...data.todos,
immutable 하게 잘 수정하셨네요.

2018-09-26 06:38 UTC, hyeyoon commented
리뷰해주신 것을 바탕으로 코드를 수정해봤습니다! :)

2018-09-26 13:49 UTC, crongro approved these changes
네 잘하셨어요.
함수크기도 적당해보이고요. 
이런방식으로 좀더 개발해보시면, 함수형방법에 좀더 익숙해지실 수 있을거에요.

리뷰는 참고하시고요.

2018-09-26 13:49 UTC, nigayo commented on index.html
> +<script type=module src="./todolist.js" charset="utf-8"></script>
오 모듈을 사용하셨군요. 잘하셨어요.

2018-09-26 13:49 UTC, nigayo commented on todolist.js
>  const printCurrentStatus = () => {
이함수 안에서 하는 것도 
 filter -> map  -> print 이런단계로 코드를 표현할  수 있을거 같아요.
pipe를 사용할 수도 있고요.

2018-09-26 13:49 UTC, nigayo commented on todolist.js
> +  if (data.commandStatus !== 'done' && value.status === data.commandStatus) {
조건문 중복이 있으니, 아래조건을 먼저체크하는 건 어떨까요? 

if( value.status !== data.commandStauts) return accumulator;

2018-09-26 13:49 UTC, nigayo commented on todolist.js
> +const runCommand = userCommand => {
참고로, 객체관계를 잘 만들어두면 조건문을 없앨수도 있긴해요.

const o = {
  add() {},
  delete() {}
}

function run(name) {
  o[name]();
}

run("add");

2018-09-26 13:49 UTC, merged